apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName}}
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.appName}}
        tier: frontend
        track: stable
    spec:
      containers:
      - name: docker-front
        image: {{ .Values.image.name}}
