apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}
spec:
  selector:
    app: {{ .Values.appName}}
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 4200
  type: LoadBalancer